# Generated by Django 5.0 on 2023-12-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_description_alter_product_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='data',
            new_name='date',
        ),
    ]
